site_name: DocOcean
site_url: https://ocean-docs.com/
theme:
  name: material
  palette:
    primary: teal
    accent: indigo
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/lightbulb-outline
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/lightbulb
    #     name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    custom_dir: overrides

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
  - attr_list
  # for admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # for formattinng
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # for lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # for images
  - md_in_html
  # for emoji
  - pymdownx.emoji:
      emoji_index:
        !!python/name:materialx.emoji.twemoji 
      # emoji_generator: !!python/name:materialx.emoji.to_svg


